package xo

// Code generated by dbtpl. DO NOT EDIT.

import (
	"time"

	"github.com/google/uuid"
)

// Таблица токенов
type RefreshToken struct {
	ID        uuid.UUID `json:"id" db:"id"`                 // Уникальный идентификатор ползователя
	Token     string    `json:"token" db:"token"`           // Значение токена
	ExpiresAt time.Time `json:"expires_at" db:"expires_at"` // Когда истекает токен
	IsRevoked bool      `json:"is_revoked" db:"is_revoked"` // Является ли отозванным
	UserID    uuid.UUID `json:"user_id" db:"user_id"`       // Идентификатор ползователя
	CreatedAt time.Time `json:"created_at" db:"created_at"` // Когда создан
}
