package xo

// Code generated by dbtpl. DO NOT EDIT.

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

// Таблица пользователей
type User struct {
	ID        uuid.UUID      `json:"id"`         // Уникальный идентификатор ползователя
	Email     string         `json:"email"`      // email ползователя
	Username  string         `json:"username"`   // username ползователя
	FullName  sql.NullString `json:"full_name"`  // Полное имя ползователя
	CreatedAt time.Time      `json:"created_at"` // Когда создан
	LastLogin sql.NullTime   `json:"last_login"` // Последний вход
	IsActive  bool           `json:"is_active"`  // Активный пользователь
}
